### ISSUE TITLE
실행결과 오류 발생

### ISSUE THREAD

**Issue by kht6163** [AIRC-KETI/long-ke-t5#2]
안녕하세요.

자연어처리를 공부중인 학생입니다. 좋은 자료 공유해주셔서 감사드립니다.

엔진 구동중에 문제점이 있어서 문의 드립니다.

source = """translate_ko2en: 제 76조 (징계의 종류) 징계처분은 다음 5 종으로 한다."""

으로 한국어 -> 영어 번역을 시도하면 

Article 76 (Types of Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary Disciplinary DisciplinaryDisciplinary Disciplinary Disciplinary Disciplinary 

이렇게 번역하던 도중에 같은 단어가 반복하는 현상이 있습니다.

혹시 이유를 알수 있을까요?

**Comment by kht6163** [comment]
![image](https://github.com/AIRC-KETI/long-ke-t5/assets/51132917/c9e3e6ae-d8f4-49ec-826d-6c57a96c15ed)

**Comment by kimsan0622** [comment]
`repetition_penalty`나 `no_repeat_ngram_size`을 활용해 튜닝해보시길 추천드립니다.
repetition_penalty는 반복 패널티로 1보다 크면 반복을 하지 않도록 유도하고 1보다 작으면 더 반복을 허용하도록 유도됩니다.
no_repeat_ngram_size는 N개 이상의 N-gram으로 이루어진 단어가 한번 나왔을경우 해당 단어가 다시는 안나오도록 강제합니다.
예를들어 no_repeat_ngram_size=3으로 설정하면 [안녕] [하] [세요]와 같이 3-gram이 나오면 [안녕] [하] [세요]는 이후 생성에서 나올 확율을 0으로 만들어 버립니다.

더 자세한 내용은 [Huggingface Generation config](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig)을 확인해보세요.

## 예시

```python
gen_seq = model.generate(
    input_ids,
    num_beams=4,
    max_length=1024,
    repetition_penalty=1.5,
)
```

## 결과
```python
"Article 76 (Types of Disciplinary Disposition) Disciplinary dispositions are made into the following five types."
```

**Comment by kht6163** [comment]
답변 감사드립니다 새해복 많이 받으세요
